### ISSUE TITLE
Enhance Session Import for new columns

### ISSUE THREAD

**Issue by rimblas** [insum-labs/conference-manager#16]
There are several new columns on the Abstract Submission Form and the import needs to be enhanced.

**Comment by jwall-insum** [comment]
Changes done:

* Update values of ks_load_mapping.display_seq to accommodate the columns:

  * "Role:Primary Presenter Email" on display_seq 33
  * "Role:Submitter Email" on display_seq 41

* Update record on ks_event_tracks.name for Kscope18 
from: "EPM Reporting, BI Analytics and Visualization"
to: "EPM Reporting, BI Analytics, and Data Visualization"

* Add to ks_event_tracks.name for Kscope18 track "Emerging Technologies"

Affected Objects: 
ks_session_load_api.plb
